### ISSUE TITLE
Copy edit

### ISSUE THREAD

**Issue by bennuttall** [raspberrypilearning/web-server-flask#2]
@LornaLynch The screenshots are missing but can you copy edit the worksheet please?

**Comment by LornaLynch** [comment]
Of course: is there a deadline on this one? Guests visiting, might take until the weekend,...

**Comment by bennuttall** [comment]
No deadline - just whenever you can.

**Comment by LornaLynch** [comment]
Should all be done now.

**Comment by bennuttall** [comment]
Thanks
